# Generated by Django 6.0.1 on 2026-01-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='duration',
            field=models.CharField(blank=True, help_text='Duration (e.g. "10 weeks")', max_length=100),
        ),
        migrations.AddField(
            model_name='program',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Numeric price for the program', max_digits=10),
        ),
    ]
